# Generated by Django 2.2.3 on 2020-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('hero', models.CharField(max_length=30)),
                ('heroin', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
